# Generated by Django 4.0.6 on 2022-08-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hang_events', '0003_hangevent_needs_hangevent_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationField',
        ),
        migrations.AddField(
            model_name='hangevent',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hangevent',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
