# Generated by Django 4.0.6 on 2022-10-03 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hang_events', '0004_delete_locationfield_hangevent_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hangevent',
            old_name='scheduled_time',
            new_name='scheduled_time_end',
        ),
        migrations.AddField(
            model_name='hangevent',
            name='scheduled_time_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
