# Generated by Django 4.0.6 on 2022-10-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hang_events', '0005_rename_scheduled_time_hangevent_scheduled_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangevent',
            name='picture',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hangevent',
            name='budget',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hangevent',
            name='latitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hangevent',
            name='longitude',
            field=models.FloatField(default=None, null=True),
        ),
    ]
