# Generated by Django 4.1.3 on 2023-03-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hang_events', '0007_remove_hangevent_needs_remove_hangevent_tasks_task_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Need',
        ),
    ]
