# Generated by Django 4.1.3 on 2023-04-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hang_events', '0010_hangevent_google_calendar_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangevent',
            name='invitation_code',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
