# Generated by Django 4.1.3 on 2023-04-15 23:34

from django.db import migrations, models
import hang_events.models


class Migration(migrations.Migration):

    dependencies = [
        ('hang_events', '0011_hangevent_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangevent',
            name='invitation_code',
            field=models.CharField(default=hang_events.models.generate_unique_invitation_code, max_length=10, unique=True),
        ),
    ]
