# Generated by Django 4.1.3 on 2023-04-16 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0048_hangeventmessagechannel'),
        ('hang_events', '0012_alter_hangevent_invitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangevent',
            name='message_channel',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.hangeventmessagechannel'),
        ),
    ]
