# Generated by Django 4.1.3 on 2023-04-16 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hang_events', '0014_archivedhangevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivedHangEvent',
        ),
        migrations.CreateModel(
            name='ArchivedHangEvent',
            fields=[
                ('hangevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hang_events.hangevent')),
            ],
            bases=('hang_events.hangevent',),
        ),
    ]
