# Generated by Django 4.1.3 on 2023-06-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hang_events', '0017_hangevent_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangevent',
            name='picture',
            field=models.CharField(max_length=2000000),
        ),
    ]
