# Generated by Django 4.0.5 on 2022-07-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messagechannel_users_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechannel',
            name='channel_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DirectMessage',
        ),
    ]
