# Generated by Django 4.0.5 on 2022-07-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messagechannel_channel_type_delete_directmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagechannel',
            name='channel_type',
        ),
    ]
