# Generated by Django 4.0.5 on 2022-07-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_messagechannel_channel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagechannel',
            name='channel_type',
        ),
        migrations.RemoveField(
            model_name='messagechannel',
            name='users',
        ),
    ]
