# Generated by Django 4.0.5 on 2022-07-02 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_remove_messagechannel_channel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechannel',
            name='channel_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagechannel',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
