# Generated by Django 4.0.6 on 2022-07-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_messagechannel_channel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechannel',
            name='name',
            field=models.CharField(default='DM', max_length=75),
            preserve_default=False,
        ),
    ]
