# Generated by Django 4.0.6 on 2022-07-21 01:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_messagechannel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
