# Generated by Django 4.0.6 on 2022-07-28 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0017_alter_message_user_alter_messagechannel_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('messagechannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.messagechannel')),
            ],
            bases=('chat.messagechannel',),
        ),
        migrations.RemoveField(
            model_name='messagechannel',
            name='channel_type',
        ),
        migrations.RemoveField(
            model_name='messagechannel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='messagechannel',
            name='owner',
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('messagechannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.messagechannel')),
                ('name', models.CharField(max_length=75)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_channels_owned', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('chat.messagechannel',),
        ),
    ]
