# Generated by Django 4.0.6 on 2022-07-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_directmessage_remove_messagechannel_channel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechannel',
            name='channel_type',
            field=models.CharField(choices=[('DM', 'Direct Message'), ('GC', 'Group Chat')], default='DM', max_length=2),
            preserve_default=False,
        ),
    ]
