# Generated by Django 4.0.6 on 2022-10-28 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0021_messagechannel_message_last_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_channels_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
