# Generated by Django 4.1.3 on 2022-11-13 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_alter_message_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='emoji',
        ),
    ]
