# Generated by Django 4.1.3 on 2023-01-23 00:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0034_remove_messagechannel_users_temp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='UserMessage',
        ),
    ]
