# Generated by Django 4.1.3 on 2023-01-23 00:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0036_message_remove_usermessage_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='message_channel',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='message_channel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.messagechannel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
