# Generated by Django 4.1.3 on 2023-01-23 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0038_alter_reaction_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.message')),
            ],
            bases=('chat.message',),
        ),
        migrations.CreateModel(
            name='MessageChannelNameChangedMessage',
            fields=[
                ('systemmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.systemmessage')),
                ('new_name', models.CharField(max_length=50)),
            ],
            bases=('chat.systemmessage',),
        ),
        migrations.CreateModel(
            name='MessageChannelUsersAddedMessage',
            fields=[
                ('systemmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.systemmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_channel_users_added_message_user', to=settings.AUTH_USER_MODEL)),
                ('users_added', models.ManyToManyField(related_name='message_channel_users_added_message_users_added', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('chat.systemmessage',),
        ),
    ]
