# Generated by Django 4.1.3 on 2023-01-27 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0040_remove_message_content_usermessage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatUserAddedMessage',
            fields=[
                ('systemmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.systemmessage')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gc_user_added_msg_adder', to=settings.AUTH_USER_MODEL)),
                ('user_added', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gc_user_added_msg_user_added', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('chat.systemmessage',),
        ),
        migrations.CreateModel(
            name='GroupChatUserRemovedMessage',
            fields=[
                ('systemmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.systemmessage')),
                ('remover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gc_user_removed_msg_remover', to=settings.AUTH_USER_MODEL)),
                ('user_removed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gc_user_removed_msg_user_removed', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('chat.systemmessage',),
        ),
        migrations.RenameModel(
            old_name='MessageChannelNameChangedMessage',
            new_name='GroupChatNameChangedMessage',
        ),
        migrations.DeleteModel(
            name='MessageChannelUsersAddedMessage',
        ),
    ]
