# Generated by Django 4.1.3 on 2023-02-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0041_groupchatuseraddedmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default='user_message', max_length=15),
            preserve_default=False,
        ),
    ]
