# Generated by Django 4.1.3 on 2023-02-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0042_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='type',
        ),
    ]
