# Generated by Django 4.1.3 on 2023-04-16 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hang_event', '0013_hangevent_message_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0048_hangeventmessagechannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='hang_event.hangevent'),
        ),
        migrations.CreateModel(
            name='HangEventUserRemovedMessage',
            fields=[
                ('systemmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.systemmessage')),
                ('hang_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hang_event.hangevent')),
                ('user_removed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='he_user_removed_msg_user_removed', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('chat.systemmessage',),
        ),
        migrations.CreateModel(
            name='HangEventUserAddedMessage',
            fields=[
                ('systemmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.systemmessage')),
                ('hang_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hang_event.hangevent')),
                ('user_added', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='he_user_added_msg_user_added', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('chat.systemmessage',),
        ),
        migrations.CreateModel(
            name='HangEventUpdatedMessage',
            fields=[
                ('systemmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.systemmessage')),
                ('updated_field', models.CharField(max_length=100)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('hang_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hang_event.hangevent')),
            ],
            bases=('chat.systemmessage',),
        ),
    ]
