# Generated by Django 4.0.5 on 2022-06-11 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageChannel',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateField()),
                ('content', models.CharField(max_length=2000)),
                ('message_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.messagechannel')),
            ],
        ),
    ]
