# Generated by Django 4.1.3 on 2023-01-19 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0031_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageChannelUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_read', models.BooleanField(default=True)),
                ('message_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.messagechannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='messagechannel',
            name='users_temp',
            field=models.ManyToManyField(related_name='message_channels_temp', through='chats.MessageChannelUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
