# Generated by Django 4.1.3 on 2023-01-19 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0033_remove_messagechannel_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagechannel',
            name='users_temp',
        ),
        migrations.AddField(
            model_name='messagechannel',
            name='users',
            field=models.ManyToManyField(related_name='message_channels', through='chats.MessageChannelUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
