# Generated by Django 4.1.3 on 2023-01-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0039_systemmessage_messagechannelnamechangedmessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='content',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
