# Generated by Django 4.1.3 on 2023-02-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0043_remove_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default='user_message', max_length=20),
            preserve_default=False,
        ),
    ]
