# Generated by Django 4.1.3 on 2023-03-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0046_remove_message_type_groupchatnamechangedmessage_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchatnamechangedmessage',
            name='type',
        ),
        migrations.RemoveField(
            model_name='groupchatuseraddedmessage',
            name='type',
        ),
        migrations.RemoveField(
            model_name='groupchatuserremovedmessage',
            name='type',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='type',
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default='user_message', max_length=40),
            preserve_default=False,
        ),
    ]
