# Generated by Django 4.1.3 on 2023-04-16 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0047_remove_groupchatnamechangedmessage_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HangEventMessageChannel',
            fields=[
                ('messagechannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chats.messagechannel')),
            ],
            bases=('chats.messagechannel',),
        ),
    ]
