# Generated by Django 4.1.3 on 2023-05-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0050_alter_messagechannel_channel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchatuseraddedmessage',
            name='adder',
        ),
        migrations.RemoveField(
            model_name='groupchatuseraddedmessage',
            name='systemmessage_ptr',
        ),
        migrations.RemoveField(
            model_name='groupchatuseraddedmessage',
            name='user_added',
        ),
        migrations.RemoveField(
            model_name='groupchatuserremovedmessage',
            name='remover',
        ),
        migrations.RemoveField(
            model_name='groupchatuserremovedmessage',
            name='systemmessage_ptr',
        ),
        migrations.RemoveField(
            model_name='groupchatuserremovedmessage',
            name='user_removed',
        ),
        migrations.RemoveField(
            model_name='hangeventupdatedmessage',
            name='hang_events',
        ),
        migrations.RemoveField(
            model_name='hangeventupdatedmessage',
            name='systemmessage_ptr',
        ),
        migrations.RemoveField(
            model_name='hangeventuseraddedmessage',
            name='hang_events',
        ),
        migrations.RemoveField(
            model_name='hangeventuseraddedmessage',
            name='systemmessage_ptr',
        ),
        migrations.RemoveField(
            model_name='hangeventuseraddedmessage',
            name='user_added',
        ),
        migrations.RemoveField(
            model_name='hangeventuserremovedmessage',
            name='hang_events',
        ),
        migrations.RemoveField(
            model_name='hangeventuserremovedmessage',
            name='systemmessage_ptr',
        ),
        migrations.RemoveField(
            model_name='hangeventuserremovedmessage',
            name='user_removed',
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='content',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GroupChatNameChangedMessage',
        ),
        migrations.DeleteModel(
            name='GroupChatUserAddedMessage',
        ),
        migrations.DeleteModel(
            name='GroupChatUserRemovedMessage',
        ),
        migrations.DeleteModel(
            name='HangEventUpdatedMessage',
        ),
        migrations.DeleteModel(
            name='HangEventUserAddedMessage',
        ),
        migrations.DeleteModel(
            name='HangEventUserRemovedMessage',
        ),
    ]
