# Generated by Django 4.1.3 on 2023-05-06 17:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0051_remove_groupchatuseraddedmessage_adder_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DirectMessage',
            new_name='DirectMessageChannel',
        ),
        migrations.RenameModel(
            old_name='GroupChat',
            new_name='GroupMessageChannel',
        ),
    ]
