# Generated by Django 4.1.3 on 2023-05-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0052_rename_directmessage_directmessagechannel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemmessage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(default='hello', max_length=2000),
            preserve_default=False,
        ),
    ]
