# Generated by Django 4.1.3 on 2023-05-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0052_rename_directmessage_directmessagechannel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemmessage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chats.message'),
        ),
    ]
