# Generated by Django 4.0.6 on 2022-08-04 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hang_event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hangevent',
            name='needs',
        ),
        migrations.RemoveField(
            model_name='hangevent',
            name='tasks',
        ),
    ]
