# Generated by Django 4.0.6 on 2022-08-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hang_event', '0002_remove_hangevent_needs_remove_hangevent_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangevent',
            name='needs',
            field=models.JSONField(default=['hi']),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hangevent',
            name='tasks',
            field=models.JSONField(default=['hi']),
            preserve_default=False,
        ),
    ]
