# Generated by Django 4.1.3 on 2023-03-03 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hang_event', '0006_hangevent_picture_alter_hangevent_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hangevent',
            name='needs',
        ),
        migrations.RemoveField(
            model_name='hangevent',
            name='tasks',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hang_event.hangevent')),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='hang_event.hangevent')),
            ],
        ),
    ]
