# Generated by Django 4.1.3 on 2023-04-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hang_event', '0008_delete_need'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangevent',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
