# Generated by Django 4.1.3 on 2023-04-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hang_event', '0013_hangevent_message_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedHangEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hang_event.hangevent',),
        ),
    ]
