export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const GETSELF = 'GETSELF';
export const GETUSER = 'GETUSER';

export const LOADROOMS = 'LOADROOMS';
export const LOADGROUPS = 'LOADGROUPS';

export const CONNECTWS = 'CONNECTWS';
export const CONNECTRTWS = 'CONNECTRTWS';

export const LOADFRIENDS = 'LOADFRIENDS';
export const LOADRECEIVEDFRIENDREQUESTS = 'LOADRECEIVEDFRIENDREQUESTS';
export const ACCEPTFRIENDREQUEST = 'ACCEPTFRIENDREQUEST';
export const DECLINEFRIENDREQUEST = 'DECLINEFRIENDREQUEST'
export const REMOVEFRIEND = 'REMOVEFRIEND';
export const BLOCKFRIEND = 'BLOCKFRIEND';
export const LOADBLOCKEDUSERS = 'LOADBLOCKEDUSERS';
export const DELETESENTFRIENDREQUEST = 'DELETESENTFRIENDREQUEST';
export const LOADSENTFRIENDREQUESTS = 'LOADSENTFRIENDREQUESTS';
export const UNBLOCKUSER = 'UNBLOCKUSER';

export const CREATEHANGEVENT = 'CREATEHANGEVENT';
export const GETHANGEVENTS = 'GETHANGEVENTS';

export const GETUNREADNOTIFICATIONS = 'GETUNREADNOTIFICATIONS';

