export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const LOADROOMS = 'LOADROOMS';
export const LOADGROUPS = 'LOADGROUPS';
export const CONNECTWS = 'CONNECTWS';

export const LOADFRIENDS = 'LOADFRIENDS';
export const LOADRECEIVEDFRIENDREQUESTS = 'LOADRECEIVEDFRIENDREQUESTS';
export const ACCEPTFRIENDREQUEST = 'ACCEPTFRIENDREQUEST';