# Generated by Django 4.0.6 on 2022-07-14 21:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_settings_is_verified_emailauthtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailAuthToken',
            new_name='EmailAuthenticationToken',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='is_verified',
            new_name='is_email_verified',
        ),
    ]
