# Generated by Django 4.0.6 on 2022-07-17 21:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_rename_emailauthtoken_emailauthenticationtoken_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailAuthenticationToken',
            new_name='EmailAuthToken',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='is_email_verified',
            new_name='is_verified',
        ),
    ]
