# Generated by Django 4.0.6 on 2022-08-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_settings_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile_picture',
            field=models.CharField(default='default profile pic change this later', max_length=200),
        ),
    ]
