# Generated by Django 4.0.6 on 2022-10-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userdetails_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailauthtoken',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
