# Generated by Django 4.1.3 on 2023-04-26 22:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_googlecalendaraccesstoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoogleCalendarAccessToken',
            new_name='GoogleAuthenticationToken',
        ),
    ]
