# Generated by Django 4.1.3 on 2023-04-27 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_googlecalendaraccesstoken_googleauthenticationtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailauthtoken',
            old_name='id',
            new_name='token',
        ),
    ]
