# Generated by Django 4.1.3 on 2023-05-05 22:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_rename_id_emailauthtoken_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailAuthToken',
            new_name='EmailAuthenticationToken',
        ),
    ]
