# Generated by Django 4.1.3 on 2023-05-06 17:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_rename_emailauthtoken_emailauthenticationtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='Profile',
        ),
    ]
