# Generated by Django 4.1.3 on 2023-05-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_userdetails_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.CharField(default='default profile pic change this later', max_length=2000),
        ),
    ]
