# Generated by Django 4.1.3 on 2023-06-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.CharField(default='/static/media/logo.76ffd1144b342263116b472f0c0cff50.svg', max_length=200000),
        ),
    ]
