# Generated by Django 4.1.3 on 2023-06-07 22:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailAuthenticationToken',
            new_name='EmailVerificationToken',
