# Generated by Django 4.1.3 on 2023-04-07 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendars', '0003_alter_manualtimerange_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoogleCalendarInformation',
            new_name='GoogleCalendarCalendars',
        ),
        migrations.CreateModel(
            name='GoogleCalendarAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=512)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
