# Generated by Django 4.1.3 on 2023-04-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_rename_googlecalendarinformation_googlecalendarcalendars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendaraccesstoken',
            name='refresh_token',
            field=models.CharField(default='asdfasdf', max_length=1024),
            preserve_default=False,
        ),
    ]
