# Generated by Django 4.1.3 on 2023-04-17 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0006_googlecalendaraccesstoken_last_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatingTimeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('repeat_interval', models.IntegerField()),
                ('repeat_count', models.IntegerField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.manualcalendar')),
            ],
        ),
    ]
