# Generated by Django 4.1.3 on 2023-04-26 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0007_repeatingtimerange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleCalendarAccessToken',
        ),
    ]
