# Generated by Django 4.1.3 on 2023-05-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0008_delete_googlecalendaraccesstoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoogleCalendarCalendars',
            new_name='GoogleCalendar',
        ),
    ]
